package com.app.laqshya.studenttracker.activity.utils

interface Constants {
    companion object {
        const val TAG_PERFORMANCE = "performance"
        const val TAG_ATTENDANCE = "attendance"
        const val TAG_NOTIFICATIONS = "notifications"
        const val TAG_DOWNLOADNOTES = "down notes"
        const val TAG_ADD_COUNSELLOR="addcounsellor"
        const val MANAGE_STUDENTS="manageStudents"
        const val SCHEDULE_BATCHES="scheduleBatches"
        const val TAGABOUT="about"
        const val TAG_DELETED="deleted"
        const val TAG_ADD_FACULTY="addFaculty"
        const val TAG_ADD_STUDENT="addStudent"
        const val BATCHID="batchid"
        const val TAG_BROADCAST = "broadcast"
        const val TAG_FEESSTATUS = "fess Status"
        const val COURSE_CATEGORY = "coursecategory"
        const val COURSE_NAME = "coursename"
        const val TAG_SYLLABUS = "syllabus"
        const val TAG_refer_friend = "refer Friend"
        const val COUNSELLOR_NAME = "counsellorname"
        const val TAG_CONTACT = "contact"
        const val BATCH_TYPE = "batchtype"
        const val TAG_ABOUT_DEVELOPERS = "aboutdevelopers"
        const val TAG_PRIVACYPOLICY = "privacypolicy"
        const val TAG_TELEPHONE = "telephone"
        const val PRIMARY_NOTIFICATION_CHANNEL = "default"
        const val TAG_WALKIN_INTERVIEW = "walkininterview"
        const val TAG_FEEDBACK = "feedback"
        const val TAG_PAYMENT = "payment"
        const val LOCATION = "location"
        const val TAG_BATCH = "batch"
        const val NAME = "NAME"
        const val USER_NAME = "USER_NAME"
        const val USER_TYPE = "USER_TYPE"
        const val Phone = "phone"
        const val USER_CENTER = "centername"
        const  val isLoggedIn = "isloggedin"
        const val Fragmenttype = "fragmentType"
        const val IS_FIRSTTIME = "isfirsttime"
        const val BATCHSTARTDATE = "batchStartDate"
        const val FCM_ID = "fcm_id"
        const val ARG_PARAM1 = "param1"
        const val TAG_HOME = "home"
        const val  COUNSELLOR="counsellor"
        const val ADMIN="admin"
        const val STUDENT="student"
        const  val TAG_ADD_SYLLABUS="add_syllabus"
        const val FACULTY="faculty"
        const val TAG_NOTES="notes"
        const val WEBSITE_URL = "http://www.laqshyainfosoft.com/privacypolicy"
        const val PAYMENT_URL = "https://easebuzz.in/pay/laqshya.in"
        const val FORM_URL = "https://docs.google.com/forms/d/10vW47C_Om9li9aIPlIrCAtH3uA5Li5OOEzJwuC7hIXo/edit"
        const val urlNavHeaderBg = "http://www.gizmobolt.com/wp-content/uploads/2014/11/14-77.jpg"
        const val urlProfileImg = "https://lh5.ggpht.com/_xFgbdzVyFUkNwZXiqgwu0YoBJSfaWk6yu9JWqe635QMb1J5EfeXLeol1-dJEE26y_c=w300"
        const val PDF_SITE_URL = "http://edutracker.in/laqshyaapp/"
        const val NOTIFICATIONID=100


    }


}